name: Load Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

permissions:
  contents: read

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Start application
        run: |
          npm run dev &
          sleep 30

      - name: Smoke test
        run: k6 run tests/load/smoke-test.js

      - name: Baseline crawl test
        run: k6 run tests/load/baseline-crawl.js

      - name: Validate targets
        run: |
          if [ -f summary.json ]; then
            if [ $(jq '.targets_met.p95_under_8min and .targets_met.abort_under_1pct' summary.json 2>/dev/null || echo "false") != "true" ]; then
              echo "⚠️ Load test failed to meet Phase 1 targets"
              exit 1
            fi
            echo "✅ Load test targets met"
          else
            echo "⚠️ No summary.json found, skipping validation"
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: load-test-results
          path: |
            summary.json
            *.log
